os:
    - linux
sudo: required
dist: trusty
language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - tree
script:
    - 'curl -s -L https://github.com/sustrik/libmill/archive/master.tar.gz | tar -zxf -'
    - 'mv libmill-master libmill'
    - 'cd libmill'
    - 'libtoolize || true'
    - './autogen.sh'
    - './configure --enable-shared=false'
    - 'make libmill.la'
    - 'cd ../'
    - 'curl -s -L https://github.com/jedisct1/libsodium/archive/master.tar.gz | tar -zxf -'
    - 'mv libsodium-master libsodium'
    - 'cd libsodium'
    - 'libtoolize || true'
    - './autogen.sh'
    - './configure --enable-shared=false'
    - 'make'
    - 'cd ../'
    - 'mkdir -p m4'
    - 'autoreconf -if'
    - 'export CPPFLAGS="-I$(pwd)/libmill -I$(pwd)/libsodium/src/libsodium/include"'
    - 'export LDFLAGS="-L$(pwd)/libmill/.libs -L$(pwd)/libsodium/src/libsodium/.libs"'
    - 'export LIBS=-lrt'
    - './configure --prefix=/usr --sysconfdir=/etc'
    - 'make'
    - 'make check'
    - 'make DESTDIR=$(pwd)/dist/ install'
    - 'tree $(pwd)/dist/'
